"""add medicine_price make potency dosage nullable

Revision ID: 161cf05f331b
Revises: 5bb4309aa1d7
Create Date: 2026-04-08 15:33:10.184501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161cf05f331b'
down_revision: Union[str, None] = '5bb4309aa1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'prescription_items',
        sa.Column('medicine_price', sa.Numeric(precision=10, scale=2), nullable=True)
    )

    op.execute(
        sa.text("UPDATE prescription_items SET medicine_price = 0 WHERE medicine_price IS NULL")
    )

    op.alter_column(
        'prescription_items',
        'medicine_price',
        existing_type=sa.Numeric(precision=10, scale=2),
        nullable=False
    )

    op.alter_column('prescription_items', 'potency',
                    existing_type=sa.VARCHAR(length=50),
                    nullable=True)
    op.alter_column('prescription_items', 'dosage',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescription_items', 'dosage',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('prescription_items', 'potency',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('prescription_items', 'medicine_price')
    # ### end Alembic commands ###
