"""add ai_usage_logs, api_request_logs, update blocked_tokens

Revision ID: 255f38d58805
Revises: b95cfd9eb23e
Create Date: 2026-05-14 19:23:38.691072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255f38d58805'
down_revision: Union[str, None] = 'b95cfd9eb23e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
