"""add doctor_availability, offline consultation fields

Revision ID: 4d29707bfa8f
Revises: fa7559735690
Create Date: 2026-04-13 21:56:02.062638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d29707bfa8f'
down_revision: Union[str, None] = 'fa7559735690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Step 1: add as nullable
    op.add_column(
        'consultations',
        sa.Column('is_offline', sa.Boolean(), nullable=True)
    )

    # Step 2: update existing rows
    op.execute("UPDATE consultations SET is_offline = false")

    # Step 3: make it NOT NULL
    op.alter_column('consultations', 'is_offline', nullable=False)
    
    op.add_column('consultations', sa.Column('created_by_doctor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'consultations', 'users', ['created_by_doctor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_column('consultations', 'created_by_doctor_id')
    op.drop_column('consultations', 'is_offline')
    op.drop_table('doctor_availability')
    # ### end Alembic commands ###
