"""add medicine_category consultation_fee delivery_charges to prescriptions

Revision ID: 5bb4309aa1d7
Revises: b1aa214c0158
Create Date: 2026-04-07 22:59:39.919497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb4309aa1d7'
down_revision: Union[str, None] = 'b1aa214c0158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedbacks_status', table_name='feedbacks')
    op.drop_index('ix_feedbacks_user_id', table_name='feedbacks')
    op.drop_index('ix_logs_created_at', table_name='logs')
    op.drop_index('ix_logs_level', table_name='logs')

    # 1) add nullable first
    op.add_column(
        'prescription_items',
        sa.Column('medicine_category', sa.String(length=100), nullable=True)
    )
    op.add_column(
        'prescriptions',
        sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True)
    )
    op.add_column(
        'prescriptions',
        sa.Column('delivery_charges', sa.Numeric(precision=10, scale=2), nullable=True)
    )

    # 2) backfill existing rows
    op.execute("""
        UPDATE prescription_items
        SET medicine_category = 'Oral Medicine'
        WHERE medicine_category IS NULL
    """)
    op.execute("""
        UPDATE prescriptions
        SET consultation_fee = 0,
            delivery_charges = 0
        WHERE consultation_fee IS NULL OR delivery_charges IS NULL
    """)

    # 3) enforce NOT NULL
    op.alter_column(
        'prescription_items',
        'medicine_category',
        existing_type=sa.String(length=100),
        nullable=False
    )
    op.alter_column(
        'prescriptions',
        'consultation_fee',
        existing_type=sa.Numeric(precision=10, scale=2),
        nullable=False
    )
    op.alter_column(
        'prescriptions',
        'delivery_charges',
        existing_type=sa.Numeric(precision=10, scale=2),
        nullable=False
    )

    op.alter_column(
        'prescriptions', 'total_amount',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescriptions', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('prescriptions', 'delivery_charges')
    op.drop_column('prescriptions', 'consultation_fee')
    op.drop_column('prescription_items', 'medicine_category')
    op.create_index('ix_logs_level', 'logs', ['level'], unique=False)
    op.create_index('ix_logs_created_at', 'logs', ['created_at'], unique=False)
    op.create_index('ix_feedbacks_user_id', 'feedbacks', ['user_id'], unique=False)
    op.create_index('ix_feedbacks_status', 'feedbacks', ['status'], unique=False)
    # ### end Alembic commands ###
