"""add icon field to ailments

Revision ID: 93abbc36168a
Revises: 23b881f43a3b
Create Date: 2026-04-18 18:23:37.471082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93abbc36168a'
down_revision: Union[str, None] = '23b881f43a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ailments', sa.Column('icon', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ailments', 'icon')
    # ### end Alembic commands ###
