"""add ai_usage_logs, api_request_logs, update blocked_tokens

Revision ID: b95cfd9eb23e
Revises: d69fda5230ed
Create Date: 2026-05-14 18:21:08.756289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95cfd9eb23e'
down_revision: Union[str, None] = 'd69fda5230ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocked_tokens', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_blocked_tokens_expires_at'), 'blocked_tokens', ['expires_at'], unique=False)
    op.create_index('ix_blocked_tokens_expires_at_blocked_at', 'blocked_tokens', ['expires_at', 'blocked_at'], unique=False)
    op.create_index(op.f('ix_blocked_tokens_user_id'), 'blocked_tokens', ['user_id'], unique=False)
    op.create_foreign_key(None, 'blocked_tokens', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blocked_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_blocked_tokens_user_id'), table_name='blocked_tokens')
    op.drop_index('ix_blocked_tokens_expires_at_blocked_at', table_name='blocked_tokens')
    op.drop_index(op.f('ix_blocked_tokens_expires_at'), table_name='blocked_tokens')
    op.drop_column('blocked_tokens', 'user_id')
    # ### end Alembic commands ###
