"""add addresses table, dob to family_members, address_id to orders and consultations

Revision ID: fa7559735690
Revises: 161cf05f331b
Create Date: 2026-04-12 18:27:07.396509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7559735690'
down_revision: Union[str, None] = '161cf05f331b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('consultations', sa.Column('address_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'consultations', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    # 1. Add dob nullable
    op.add_column('family_members', sa.Column('dob', sa.Date(), nullable=True))

    # 2. Convert age → dob (approx)
    op.execute("""
        UPDATE family_members
        SET dob = CURRENT_DATE - (age || ' years')::interval
    """)

    # 3. Make NOT NULL
    op.alter_column('family_members', 'dob', nullable=False)

    # 4. Drop age
    op.drop_column('family_members', 'age')
    
    op.add_column('orders', sa.Column('address_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'address_id')
    op.add_column('family_members', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('family_members', 'dob')
    op.drop_constraint(None, 'consultations', type_='foreignkey')
    op.drop_column('consultations', 'address_id')
    op.drop_table('addresses')
    # ### end Alembic commands ###
